name: GitHub Actions for Assessment of Trivago Co.
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    tags:
    - "*"
    paths:
    - appv2/*
env:
  REG_ACCOUNT: manouchehrsolamani
  PROJECT: trivago
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Scan Dockerfile using Checkov
        continue-on-error: true
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: appv2
          framework: dockerfile
          quiet: true 
          container_user: 1000

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push container image
        uses: docker/build-push-action@v4
        with:
          context: appv2
          push: true
          tags: ${{ env.REG_ACCOUNT }}/${{ env.PROJECT }}:v2
          # tags: ${{ env.PROJECT }}/${{ env.IMAGE2 }}:${{ github.ref }}:${{ github.sha }}